### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/UKSEABMLib.jl#31]
potential performance improvement by a variety of ways: 

- [x] Implementation of removeDeads (making use of the index of the deads) 
- [x] getting rid of the use of global variables #20 
- [ ] doX! with the exact subpopulation #21 
     - [x] alive sub-population
     - [ ] male & female sub-populations   
     - [ ] maintaining sub-populations with minimal efforts 
- [x] MultiAgents.jl (existing potential type instability) 
- [x] make outputs of simulation functions become an argument (of type struct) #29  
- [x] improve implementation of allocation to other houses #23 
     - [x] improve implementation of finding empty houses, 
     - [x] investigate if it is worth to make related functions, e.g. select_house return only one type
     - [ ] caching pre-computations (e.g. weight towns). Similar stuffs have been done and improved performance
     - [ ] caching adjacent towns 
     - [ ] caching town densities   
     - [x] caching inst. prop. (slight improvement for large-size populations done only with birth function) 
     - [ ] same with other functions 
- [x] #37
- [x] #40
- [ ] #41  
- [x] #44 (partially improved)
- [ ] #30 (partially improved)
- [ ] trying struct of arrays pattern 
- [ ] noperson()::Person instead of nothing::Type{Nothing}
- [ ] algorithmic / technical
     - [ ] removing many agents / deads at once  
     - [x] views of arrays instead of copies (tiny stuffs)
- [ ]  conducing consistency checking and assertion along unit tests #60
